export const AFFORDMED_CONFIG = {
  BASE_URL: "http://4.224.186.213/evaluation-service",

  CLIENT_ID: "REPLACE_CLIENT_ID",
  CLIENT_SECRET: "REPLACE_CLIENT_SECRET",
  ACCESS_CODE: "REPLACE_ACCESS_CODE",
  ACCESS_TOKEN: "REPLACE_ACCESS_TOKEN",

  EMAIL: "REPLACE_EMAIL",
  ROLL_NO: "REPLACE_ROLL_NO",
  NAME: "REPLACE_NAME"
};